[package]
name = "olc_utils"
version = "0.1.0"
edition = "2021"

[dependencies]
radium = "1.1.0"
bytemuck = { version = "1.19.0",features = ["derive","zeroable_atomics"] }
libc = "0.2.161"

[features]
track-thread-locks=[]